### ISSUE TITLE
Switch to a different test framework

### ISSUE THREAD

**Issue by koterpillar** [koterpillar/aloe#108]
Nose is [in maintenance mode](http://nose.readthedocs.org/). Should switch to a different framework.

![](http://www.100bestbooks.ru/pictures/books/Gogol_Nos.jpg)

**Comment by koterpillar** [comment]
Plain unittest under 2.7 isn't very nice, it uses not even optparse but getopt. There are no backports from 3.

**Comment by koterpillar** [comment]
http://nose2.readthedocs.org/en/latest/configuration.html#when-loading-plugins-from-modules-is-not-enough can help with Nose2.

**Comment by koterpillar** [comment]
Django-nose is not actively maintained either and is not likely to be updated for Django 1.10.

**Comment by koterpillar** [comment]
Django-nose luckily got patches for 1.10; no optparse there anymore.

**Comment by jrd** [comment]
Is a switch to pytest considered?
Can I help?

I saw a branch about it but seems a bit old… I would be ok to port this to pytest with some help

**Comment by koterpillar** [comment]
I've tried to port this to plain unittest but found that it's not extensible enough (especially bringing Django in the mix). If Pytest can support Aloe _and_ Django without horrible hacks, it would be a nice way forward.

**Comment by nikolas** [comment]
nose is pretty old by now, and won't run on current versions of python. It doesn't looks like [nose2](https://github.com/nose-devs/nose2/tree/main/nose2/tools) has the same API as `nose`, so I'm not sure how much work it is for a port to nose2. Maybe we can take another look to migrate aloe from nose to plain [unittest](https://docs.python.org/3/library/unittest.html), as a lot has changed since 2018 and maybe this is possible now.
