### ISSUE TITLE
Is making the string raw for the step is neccessary?

### ISSUE THREAD

**Issue by GalRogozinski** [koterpillar/aloe#144]
Hey,

I am working with VS code and installed the Gherkin plugin. The plugin fails to connect the feature file to the steps file beacuse of the `r` (raw) prefix that I added to the string.

In order to make the plugin work I deleted the `r` prefix. To my surprise aloe kept on working.
For example this works:
```
@step(`my step (\d+)`)
def my_step(step, number)
      print(number)
      assert False
```

However, I am afraid to go against the docs just to get VS code support. 
Is it fine that I omit the `r`?

**Comment by koterpillar** [comment]
The `r` is not required.

```python
r'my step (\d+)' == 'my step (\d+)'
# True
```

It is there so that Python does not try to parse `\d` as an [escape sequence](https://docs.python.org/3/reference/lexical_analysis.html) (search for "Escape Sequence" on that page) and output a warning:

```shell
$ python -W all -c 'print("\d")'
<string>:1: DeprecationWarning: invalid escape sequence \d
\d
```

Note that your syntax with backticks (`) is invalid, you probably meant quotes.

I suggest notifying the authors of the Gherkin plugin that they need to recognize the raw strings as well.
